* MarmotOS
MarmotOS is a basic, experimental operating system written in Rust. Named after marmots, because marmots are cool.

** What is this?
It's a toy - an experiment.
All three of the maintainers are (at the time of writing) college students studying Computer Science or Computer Engineering. We were fascinated by classes that taught us how computers worked, so we wanted to take a stab at it.
Hopefully, by implementing this, not only will we get to apply what we've learned, but learn even more that we weren't taught.

Rust was chosen because it's neat. It seems to be one of the future languages of systems programming, so we figured we'd use it for such a purpose.

** End Goals
Our primary end goal is a basic userspace that allows for navigating the file system, editing files, running programs, and other similar tasks. This, of course, will be underpinned by managed virtual memory and process scehduling.
We'd also like to do a few other things, such as:
- Implement a full network stack
- Run C programs that link to the C Standard Library

However, those are stretch goals - the primary goal is the basic userspace. These goals may be lofty, but we hope to achieve them eventually.

-----
All rights reserved. If you're learning how to make rocks think like us, feel free to use this code as a reference.
